export const CONSTANTS = {
  FIN_SURFBOARD: "Dérives de surf",
  LEASH: "Leash de surf",
  NEOPRENE_JACKET: "Veste néopréne",
  KITE_WING: "Aile de Kite Surf",
  HARNESS_KYTE: "Harnais de Kite Surf",
  PAD: "Pad de surf",
  BORDYBOARD_FIN: "Palmes de bodyboard",
  BORDYBOARD: "Planche de bodyboard",
  IMPACT_JACKET: "Gilet Impact de surf",
  TOP: "Lycra / Top",
  BOOTTIES: "Chaussons néopréne",
  BLALACLAVA: "Cagoules / Bonnets",
  GLOVES: "Gants néopréne",
  SURFBOARD: "Planche de Surf",
  LUGGAGE_BODYBOARD: "Bagagerie de bodyboard",
  SURF_ACCESSORIES: "Accessoires de surf",
  LEASH_COIL: "Leash coil",
  BODYBOARD_ACCESSORIES: "Accessoires de bodyboard",
  KITESURF_BAR: "Barre de Kite Surf",
  LUGGAGE_SURF: "Bagagerie de surf",
  FULL_WETSUIT: "Combinaison intégrale",
  SEMI_WETSUIT: "Combinaison shorty",
  LONGJOHN: "Long John",
  TWINTIP: "Twin-Tip de Kite Surf",
};
